RahaAirline/Areas/Admin/Controllers/ResidencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace RahaAirline.Areas.Admin.Controllers
{
    [Authorize(Users = "admin@example.com")]
    public class ResidencesController : Controller
    {
        private IResidenceRepository residenceRepository;
        private IResidenceTypeRepository residenceTypeRepository;
        private RahaAirlineContext db = new RahaAirlineContext();

        public ResidencesController()
        {
            residenceRepository=new ResidenceRepository(db);
            residenceTypeRepository=new ResidenceTypeRepository(db);
        }
        // GET: Admin/Residences
        public ActionResult Index()
        {
           
            return View(residenceRepository.GetAllResidences());
        }

        // GET: Admin/Residences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Residence residence = db.Residences.Find(id);
            if (residence == null)
            {
                return HttpNotFound();
            }
            return View(residence);
        }

        // GET: Admin/Residences/Create
        public ActionResult Create()
        {
            ViewBag.ResidenceTypeID = new SelectList(residenceTypeRepository.GetAllResidenceTypes(), "ResidenceTypeID", "ResidenceKind");
            return View();
        }

        // POST: Admin/Residences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResidenceID,ResidenceTypeID,Location,Image,CheckIn,CheckOut,Price,Visit,ShortDescription,Text,CreateDate,Tag")] Residence residence,HttpPostedFileBase imgResidence)
        {
            if (ModelState.IsValid)
            {
                residence.Visit = 0;
                residence.CreateDate = DateTime.Now;
                residence.CheckIn = DateTime.Now.ToString();
                residence.CheckOut = DateTime.Now.ToString();
                if (imgResidence != null)
                {
                    residence.Image = Guid.NewGuid() + Path.GetExtension(imgResidence.FileName);
                    imgResidence.SaveAs(Server.MapPath("/ResidenceImages/" + residence.Image));
                }
                residenceRepository.InsertResidence(residence);
                residenceRepository.Save();
                return RedirectToAction("Index");
            }

            ViewBag.ResidenceTypeID = new SelectList(residenceTypeRepository.GetAllResidenceTypes(), "ResidenceTypeID", "ResidenceKind", residence.ResidenceTypeID);
            return View(residence);
        }

        // GET: Admin/Residences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Residence residence = residenceRepository.GetResidenceById(id.Value);
            if (residence == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResidenceTypeID = new SelectList(residenceTypeRepository.GetAllResidenceTypes(), "ResidenceTypeID", "ResidenceKind", residence.ResidenceTypeID);
            return View(residence);
        }

        // POST: Admin/Residences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResidenceID,ResidenceTypeID,Location,Image,CheckIn,CheckOut,Price,Visit,ShortDescription,Text,CreateDate,Tag")] Residence residence,HttpPostedFileBase imgResidence)
        {
            if (ModelState.IsValid)
            {
                if (imgResidence != null)
                {
                    if (residence.Image != null)
                    {
                        System.IO.File.Delete(Server.MapPath("/ResidenceImages/" + residence.Image));
                    }


                    residence.Image = Guid.NewGuid() + Path.GetExtension(imgResidence.FileName);
                    imgResidence.SaveAs(Server.MapPath("/ResidenceImages/" + residence.Image));
                }

                residenceRepository.UpdateResidence(residence);
                residenceRepository.Save();
                return RedirectToAction("Index");
            }
            ViewBag.ResidenceTypeID = new SelectList(residenceTypeRepository.GetAllResidenceTypes(), "ResidenceTypeID", "ResidenceKind", residence.ResidenceTypeID);
            return View(residence);
        }

        // GET: Admin/Residences/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Residence residence = residenceRepository.GetResidenceById(id.Value);
            if (residence == null)
            {
                return HttpNotFound();
            }
            return View(residence);
        }

        // POST: Admin/Residences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Residence residence =residenceRepository.GetResidenceById(id);
            if (residence.Image != null)
            {
                System.IO.File.Delete(Server.MapPath("/ResidenceImages/" + residence.Image));
            }
            residenceRepository.DeleteResidence(residence);
            residenceRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                residenceRepository.Dispose();
                residenceTypeRepository.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RahaAirline/Areas/Admin/Views/Residences/Create.cshtml
@model DataLayer.Residence

@{
    ViewBag.Title = "Create";
}

<h2>ایجاد</h2>

@using (Html.BeginForm("Create", "Residences", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ResidenceTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResidenceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResidenceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imgResidence" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.CheckIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section scripts
{
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Text').ckeditor();
        });
    </script>

}

RahaAirline/Areas/Admin/Views/Residences/Delete.cshtml
@model DataLayer.Residence

@{
    ViewBag.Title = "Delete";
}

<h2>حذف</h2>

<h3>آیا از حذف این مورد مطمئن هستید؟</h3>
<div>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ResidenceType.ResidenceKind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResidenceType.ResidenceKind)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="/ResidenceImages/@Model.Image" class="thumbnail" style="max-width: 150px" />
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Visit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Visit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-danger" />
         
        </div>
    }
</div>

RahaAirline/Areas/Admin/Views/Residences/Details.cshtml
@model DataLayer.Residence

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Residence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ResidenceType.ResidenceKind)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResidenceType.ResidenceKind)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ResidenceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RahaAirline/Areas/Admin/Views/Residences/Edit.cshtml
@model DataLayer.Residence

@{
    ViewBag.Title = "Edit";
}

<h2>ویرایش</h2>

@using (Html.BeginForm("Edit", "Residences", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ResidenceID)
        @Html.HiddenFor(model => model.CreateDate)
        @Html.HiddenFor(model => model.CheckIn)
        @Html.HiddenFor(model => model.CheckOut)

        <div class="form-group">
            @Html.LabelFor(model => model.ResidenceTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ResidenceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResidenceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imgResidence" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })

                @if (Model.Image != null)
                {
                    <img src="/ResidenceImages/@Model.Image" class="thumbnail" style="max-width: 150px" />
                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.CheckIn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckIn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckOut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckOut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

@section scripts
{
    <script src="/ckeditor/ckeditor.js"></script>
    <script src="/ckeditor/adapters/jquery.js"></script>
    <script>
        $(function () {
            $('#Text').ckeditor();
        });
    </script>

}

RahaAirline/Areas/Admin/Views/Residences/Index.cshtml
@model IEnumerable<DataLayer.Residence>

@{
    ViewBag.Title = "Index";
}



<p>
    @Html.ActionLink("جدید", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ResidenceType.ResidenceKind)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Visit)
        </th> 
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CheckIn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckOut)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ResidenceType.ResidenceKind)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            <img src="/ResidenceImages/@item.Image" class="thumbnail" style="max-width: 120px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Visit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @item.CreateDate.ToShamsi()
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CheckIn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckOut)
        </td>*@
        <td>
            @Html.ActionLink("ویرایش", "Edit", new { id=item.ResidenceID }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.ResidenceID }) |*@
            @Html.ActionLink("حذف", "Delete", new { id=item.ResidenceID })
        </td>
    </tr>
}

</table>