RahaAirline/Areas/Admin/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using System.IO;

namespace RahaAirline.Areas.Admin.Controllers
{
    [Authorize(Users = "admin@example.com")]
    public class PlacesController : Controller
    {
        private IPlaceRepository placeRepository;
        RahaAirlineContext db = new RahaAirlineContext();
        public PlacesController()
        {
            placeRepository = new PlaceRepository(db);
        }

        // GET: Admin/Places
        public ActionResult Index()
        {
            return View(placeRepository.GetAllPlaces());
        }

        // GET: Admin/Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = placeRepository.GetPlaceById(id.Value);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Admin/Places/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaceID,Country,City,Image,Price,Visit")] Place place, HttpPostedFileBase imgPlace)
        {
            if (ModelState.IsValid)
            {
                place.Visit = 0;
                if (imgPlace != null)
                {
                    place.Image = Guid.NewGuid() + Path.GetExtension(imgPlace.FileName);
                    imgPlace.SaveAs(Server.MapPath("/PlaceImages/" + place.Image));
                }

                placeRepository.InsertPlace(place);
                placeRepository.Save();
                return RedirectToAction("Index");
            }

            return View(place);
        }

        // GET: Admin/Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = placeRepository.GetPlaceById(id.Value);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Admin/Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaceID,Country,City,Image,Price,Visit")] Place place, HttpPostedFileBase imgPlace)
        {
            if (ModelState.IsValid)
            {
                if (imgPlace != null)
                {
                    if (place.Image != null)
                    {
                        System.IO.File.Delete(Server.MapPath("/PlaceImages/" + place.Image));
                    }


                    place.Image = Guid.NewGuid() + Path.GetExtension(imgPlace.FileName);
                    imgPlace.SaveAs(Server.MapPath("/PlaceImages/" + place.Image));
                }

                placeRepository.UpdatePlace(place);
                placeRepository.Save();
                return RedirectToAction("Index");
            }
            return View(place);
        }

        // GET: Admin/Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = placeRepository.GetPlaceById(id.Value);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Admin/Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var place = placeRepository.GetPlaceById(id);
            if (place.Image != null)
            {
                System.IO.File.Delete(Server.MapPath("/PlaceImages/" + place.Image));
            }
            placeRepository.DeletePlace(id);
            placeRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                placeRepository.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RahaAirline/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>پنل مدیر سایت</title>

    
    <link href="~/Content/bootstrap.rtl.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("وبلاگ", "Index", "Categories", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("اقامتگاه ها", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("پروازها", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })|
                @Html.ActionLink("مکان ها", "Index", "Places", new { area = "" }, new { @class = "navbar-brand" })*@
                <a href="~/Home/Index" style="font-family: cursive; font-size: 22px; color: White;">صفحه اصلی</a> |

                <a href="~/Admin/Categories/Index" style="font-family: cursive; font-size: 18px; color: White;">دسته بندی</a> |
                <a href="~/Admin/Pages/Index" style="font-family: cursive; font-size: 18px; color: White;"> صفحات</a> |
                <a href="~/Admin/Places/Index" style="font-family: cursive; font-size: 18px; color: White;">مکان ها </a> |
                <a href="~/Admin/Residences/Index" style="font-family: cursive; font-size: 18px; color: White;">اقامتگاه ها</a> |
                <a href="~/Admin/ResidenceTypes/Index" style="font-family: cursive; font-size: 18px; color: White;">نوع اقامتگاه</a> |
                <a href="~/Admin/Flights/Index" style="font-family: cursive; font-size: 18px; color: White;">پروازها</a> |
                <a href="~/Admin/FlightClasses/Index" style="font-family: cursive; font-size: 18px; color: White;">کلاس پرواز</a> |
                <a href="~/Admin/Services/Index" style="font-family: cursive; font-size: 18px; color: White;">خدمات</a> |
                <a href="~/Admin/UserMessages/Index" style="font-family: cursive; font-size: 18px; color: White;">پیام ها</a> |


            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.ToShamsi()</p>
        </footer>
    </div>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <script src="~/Scripts/jquery.validate.js"></script>

    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @RenderSection("scripts", required: false)
    @RenderSection("script", required: false)
</body>
</html>

RahaAirline/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>پنل مدیر سایت</title>

    <!-- Core CSS - Include with every page -->
    <link href="/Areas/Admin/AdminTemplate/css/bootstrap-rtl.css" rel="stylesheet">
    <link href="/Areas/Admin/AdminTemplate/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Areas/Admin/AdminTemplate/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />

    <!-- Page-Level Plugin CSS - Blank -->
    <!-- SB Admin CSS - Include with every page -->
    <link href="/Areas/Admin/AdminTemplate/css/sb-admin.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Admin/Categories/Index">پنل مدیر سایت</a>

            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-left">
                <li class="dropdown">
                    <a href="~/Admin/UserMessages/Index">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>

                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="~/UsersAdmin/Index"><i class="fa fa-user fa-fw"></i> مدیریت کاربران</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="~/Account/SignOut"><i class="fa fa-sign-out fa-fw"></i> خروج</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">
                        @*<li class="sidebar-search">
                                <div class="input-group custom-search-form">
                                    <input type="text" class="form-control" placeholder="جستجو">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div>
                                 /input-group
                            </li>*@
                        <li>
                            <a href="~/Home/Main"><i class="glyphicon glyphicon-home"></i> صفحه اصلی</a>
                        </li>
                        <li>
                            <a href=""><i class="glyphicon glyphicon-list-alt"></i> وبلاگ<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Admin/Categories/Index">دسته بندی ها</a>
                                </li>
                                <li>
                                    <a href="~/Admin/Pages/Index">صفحات</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>


                        <li>
                            <a href=""><i class="fa fa-home fa-fw"></i>اقامتگاه <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Admin/ResidenceTypes/Index">نوع اقامتگاه</a>
                                </li>
                                <li>
                                    <a href="~/Admin/Residences/Index">اقامتگاه ها</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        <li>
                            <a href=""><i class="fa fa-plane fa-fw"></i>پرواز <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Admin/FlightClasses/Index">کلاس پرواز</a>
                                </li>
                                <li>
                                    <a href="~/Admin/Flights/Index">پرواز ها</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                        @*<li>
                                <a href="~/Admin/Places/Index"><i class="fa fa-location-arrow fa-fw"></i> مکان ها</a>

                            </li>*@
                        <li>
                            <a href="~/Admin/Services/Index"><i class="glyphicon glyphicon-cog"></i>خدمات</a>

                        </li>
                        <li>
                            <a href="~/RolesAdmin/Index"><i class="fa fa-check fa-fw"></i> نقش ها</a>

                        </li>
                        <li>
                            <a href=""><i class="glyphicon glyphicon-list-alt"></i>گزارش رزروها <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Admin/ReservesReport/FlightReserveReport">رزروهای پرواز</a>
                                </li>
                                <li>
                                    <a href="~/Admin/ReservesReport/HotelReserveReport">رزروهای اقامتگاه</a>
                                </li>

                            </ul>
                            <!-- /.nav-second-level -->
                        </li>

                    </ul>
                    <!-- /#side-menu -->
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>


        <div id="page-wrapper">
            @RenderBody()
            @*<div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Blank</h1>
                    </div>
                     /.col-lg-12
                </div>*@
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Core Scripts - Include with every page -->
    <script src="/Areas/Admin/AdminTemplate/js/jquery-1.10.2.js"></script>
    <script src="/Areas/Admin/AdminTemplate/js/bootstrap.min.js"></script>
    <script src="/Areas/Admin/AdminTemplate/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Areas/Admin/AdminTemplate/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/Areas/Admin/AdminTemplate/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <!-- Page-Level Plugin Scripts - Blank -->
    <!-- SB Admin Scripts - Include with every page -->
    <script src="/Areas/Admin/AdminTemplate/js/sb-admin.js"></script>

    <!-- Page-Level Demo Scripts - Blank - Use for reference -->
    @RenderSection("scripts", required: false)
    @RenderSection("script", required: false)
</body>

</html>